# Generated by Django 6.1 on 2026-08-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'To do'), ('in-progress', 'In progress'), ('review', 'Review'), ('done', 'Done'), ('archive', 'Archive'), ('trash', 'Trash')], max_length=20, verbose_name='status'),
        ),
    ]
